CREATE TABLE IF NOT EXISTS `products` (
    `id`          INT UNSIGNED   NOT NULL AUTO_INCREMENT,
    `bot_id`      INT UNSIGNED   NOT NULL,
    `category_id` INT UNSIGNED   NULL,
    `name`        VARCHAR(255)   NOT NULL,
    `slug`        VARCHAR(280)   NOT NULL,
    `description` TEXT           NULL,
    `sku`         VARCHAR(100)   NULL,
    `image_url`   VARCHAR(500)   NULL,
    `price`       DECIMAL(15,2)  NOT NULL DEFAULT 0.00,
    `sale_price`  DECIMAL(15,2)  NULL,
    `stock`       INT            NOT NULL DEFAULT -1 COMMENT '-1 = unlimited',
    `status`      ENUM('active','inactive','out_of_stock') NOT NULL DEFAULT 'active',
    `sort_order`  SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    `created_at`  DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at`  DATETIME       NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_bot_slug` (`bot_id`, `slug`),
    INDEX `idx_bot_id` (`bot_id`),
    INDEX `idx_category_id` (`category_id`),
    INDEX `idx_status` (`status`),
    CONSTRAINT `fk_products_bot`      FOREIGN KEY (`bot_id`)      REFERENCES `bots` (`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_products_category` FOREIGN KEY (`category_id`) REFERENCES `categories` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
